image: node:16.16.0
pipelines:
  branches:
    feature/*:
      - step:
          name: Install Vercel CLI, Pull Vercel Preview Environment Information, Build Project Artifacts and Deploy Project Artifacts to Vercel
          script:
            - npm install --global vercel
            - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
            - vercel build --token=$VERCEL_TOKEN
            - vercel deploy --prebuilt  --token=$VERCEL_TOKEN
    main:
      - step:
          name: Install Vercel CLI, Pull Vercel Production Environment Information, Build Project Artifacts and Deploy Project Artifacts to Vercel
          script:
            - npm install --global vercel
            - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            - vercel build --prod --token=$VERCEL_TOKEN
            - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
